
group = www-data
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
listen.allowed_clients = 127.0.0.1

pm = ondemand
pm.process_idle_timeout = 10s
pm.max_requests = 5000
pm.status_path = /fpm-status
ping.path = /fpm-ping
ping.response = pong
slowlog = /var/log/php/fpm-$pool-slow.log
request_slowlog_timeout = 10s
listen.backlog = 65535

env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin

php_admin_value[default_socket_timeout] = 180
php_admin_value[max_execution_time] = 180
php_admin_value[max_input_time] = 180
php_admin_value[memory_limit] = 395M

php_admin_value[opcache.error_log] = /var/log/php/opcache-$pool-error.log
php_admin_value[opcache.log_verbosity_level] = 1

php_admin_flag[apc.enabled] = on

