#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin
SHELL=/bin/bash
_H_USER=EDIT_USER

check_root() {
  if [ `whoami` = "root" ]; then
    ionice -c2 -n7 -p $$
    renice 19 -p $$
    chmod a+w /dev/null
    if [ ! -e "/dev/fd" ]; then
      if [ -e "/proc/self/fd" ]; then
        rm -rf /dev/fd
        ln -s /proc/self/fd /dev/fd
      fi
    fi
  else
    echo "ERROR: This script should be ran as a root user"
    exit 1
  fi
  _DF_TEST=$(df -kTh / -l \
    | grep '/' \
    | sed 's/\%//g' \
    | awk '{print $6}' 2> /dev/null)
  _DF_TEST=${_DF_TEST//[^0-9]/}
  if [ ! -z "${_DF_TEST}" ] && [ "${_DF_TEST}" -gt "90" ]; then
    echo "ERROR: Your disk space is almost full !!! ${_DF_TEST}/100"
    echo "ERROR: We can not proceed until it is below 90/100"
    exit 1
  fi
}
check_root

count_cpu() {
  _CPU_INFO=$(grep -c processor /proc/cpuinfo 2>&1)
  _CPU_INFO=${_CPU_INFO//[^0-9]/}
  _NPROC_TEST=$(which nproc 2>&1)
  if [ -z "${_NPROC_TEST}" ]; then
    _CPU_NR="${_CPU_INFO}"
  else
    _CPU_NR=$(nproc 2>&1)
  fi
  _CPU_NR=${_CPU_NR//[^0-9]/}
  if [ ! -z "${_CPU_NR}" ] \
    && [ ! -z "${_CPU_INFO}" ] \
    && [ "${_CPU_NR}" -gt "${_CPU_INFO}" ] \
    && [ "${_CPU_INFO}" -gt "0" ]; then
    _CPU_NR="${_CPU_INFO}"
  fi
  if [ -z "${_CPU_NR}" ] || [ "${_CPU_NR}" -lt "1" ]; then
    _CPU_NR=1
  fi
}

load_control() {
  if [ -e "/root/.barracuda.cnf" ]; then
    source /root/.barracuda.cnf
    _CPU_SPIDER_RATIO=${_CPU_SPIDER_RATIO//[^0-9]/}
  fi
  if [ -z "${_CPU_SPIDER_RATIO}" ]; then
    _CPU_SPIDER_RATIO=3
  fi
  _O_LOAD=$(awk '{print $1*100}' /proc/loadavg 2>&1)
  _O_LOAD=$(( _O_LOAD / _CPU_NR ))
  _O_LOAD_SPR=$(( 99 * _CPU_SPIDER_RATIO ))
}

action() {
  if [ "${_O_LOAD}" -lt "${_O_LOAD_SPR}" ]; then
    ### echo "load is ${_O_LOAD} while maxload is ${_O_LOAD_SPR}"
    buildTest="1"
    tpDir="/data/disk/${_H_USER}/.tmp"
    ceDir="${tpDir}/cache"
    dlDir="${ceDir}/download"
    gtDir="${ceDir}/git"
    clCtr="/data/disk/${_H_USER}/static/control/clear-drush-cache.info"
    if [ -e "${tpDir}" ]; then
      buildTest=$(ls ${tpDir} | grep "_tmp_" | wc -l | tr -d "\n" 2>&1)
      buildTest=${buildTest//[^0-9]/}
    fi
    if [ -e "${clCtr}" ]; then
      if [ -e "${gtDir}" ] || [ "${buildTest}" -ge "1" ]; then
        rm -rf ${tpDir}/*
        rm -f ${clCtr}
        buildTest="0"
      fi
    fi
    if [ "${buildTest}" = "0" ] && [ -e "${gtDir}" ]; then
      rm -rf ${gtDir}
      rm -rf ${dlDir}
    fi
    if [ "${buildTest}" = "0" ] \
      || [ -z "${buildTest}" ] \
      || [ ! -e "${ceDir}" ]; then
      su -s /bin/bash - ${_H_USER} -c "drush8 cc drush" &> /dev/null
      su -s /bin/bash - ${_H_USER} -c "bash /data/disk/${_H_USER}/aegir.sh"
      touch /var/xdrago/log/last-run-${_H_USER}
    else
      touch /var/xdrago/log/skip-run-${_H_USER}
    fi
  fi
}

if [ -e "/var/run/boa_wait.pid" ] \
  || [ -e "/var/run/manage_rvm_users.pid" ] \
  || [ -e "/data/disk/${_H_USER}/backups/tmp_expim/metadata" ]; then
  touch /var/xdrago/log/wait-${_H_USER}
  exit 0
else
  count_cpu
  load_control
  action
  exit 0
fi
