#!/bin/bash

###-------------SYSTEM-----------------###

# Furtive (stealth) port scan protection:
/sbin/iptables -A INPUT -p tcp --tcp-flags SYN,ACK,FIN,RST SYN -m limit --limit 1/s -j ACCEPT

# Syn-flood protection:
/sbin/iptables -A INPUT -p tcp --syn -m limit --limit 1/s -j ACCEPT

# Ping of death:
/sbin/iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT

# log iptables denied calls
/sbin/iptables -A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7

# Run combo filters
/var/xdrago/run_all

echo "1" > /var/xdrago/log/blackIP.log
/sbin/iptables --list > /var/xdrago/log/fire_restart.done
echo Done!
