#!/bin/bash

LOW_LOAD=500
LOAD=`awk '{print $1*100}' /proc/loadavg`

if [ $LOAD -lt $LOW_LOAD ]; then
    touch /var/xdrago/log/fire.pid
    /var/xdrago/firewall.sh stop
    /sbin/iptables -P INPUT   ACCEPT
    /sbin/iptables -P FORWARD ACCEPT
    /sbin/iptables -P OUTPUT  ACCEPT
    /sbin/iptables --flush
    /var/xdrago/firewall_restarter
    rm -f /var/xdrago/log/fire.pid
    touch /var/xdrago/log/lastFire
fi

exit 0
