#!/bin/bash

if test -f /var/xdrago/log/optimize_mysql_ao.pid ; then
  touch /var/xdrago/log/wait-for-mysql-restart
  exit
else
  /etc/init.d/mysql restart
  touch /var/xdrago/log/last-mysql-restart-done
fi
