#!/bin/bash

### BEGIN INIT INFO
# Provides:		valkey-server
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:    valkey-server - Persistent key-value db
# Description:          valkey-server - Persistent key-value db
### END INIT INFO

PATH=/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
DAEMON=/usr/bin/valkey-server
DAEMON_ARGS=/etc/valkey/valkey.conf
NAME=valkey-server
DESC=valkey-server
PIDFILE=/run/valkey/valkey.pid

test -x $DAEMON || exit 0

[ ! -e "/run/valkey" ] && mkdir -p /run/valkey
[ -e "/run/valkey" ] && chown -R valkey:valkey /run/valkey

set -e

maxclients=$(awk '/^[ \t]*maxclients[ \t]/ { print $2 }' /etc/valkey/valkey.conf)
if [ ! -z "$maxclients" ] && [ "$maxclients" -gt 992 ]; then
  ulimit -n $((maxclients+32))
fi

case "$1" in
  start)
	echo -n "Starting $DESC: "
	touch $PIDFILE
	chown valkey:valkey $PIDFILE
	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid valkey:valkey --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --retry 8 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	sleep 1
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  reload)
    echo -n "Reloading service ${NAME}..."
    if [ ! -r ${PIDFILE} ]; then
      echo "warning, no pid file found - ${NAME} is not running ?"
      exit 1
    fi
    kill -USR2 `cat ${PIDFILE}`
    echo " done"
	;;

  status)
	echo -n "$DESC is "
	if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
	then
		echo "running"
	else
		echo "not running"
		exit 1
	fi
	;;

  *)
	echo "Usage: service $NAME {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
