#!/bin/bash

# ai_policy.sh — per-site AI bot policy, GLOBAL across all Octopus instances.
#
# Abstraction of the per-Octopus nginx_ip_access_<oct>.sh pattern: a single
# script that loops over every Octopus instance under /data/disk/<oct> which has
# an ACTIVATED control file at /data/disk/<oct>/static/control/ai/policy.txt, and
# for each generates per-site nginx fragments into that instance's own
# /data/disk/<oct>/config/includes/ai_policy/<site>.conf — exactly the path the
# per-satellite vhost pulls via `include $server->include_path/ai_policy/<uri>*`.
#
# Control records: `<site>  [train-allow] [search-block] [user-block] [utility-block]`
# turning the global AI default (training blocked; search/user/utility allowed +
# rate-limited) on/off for that site:
#   train-allow    -> set $ai_train_allow 1;            (allow AI training)
#   search-block   -> if ($is_ai_search)  { return 444; }
#   user-block     -> if ($is_ai_user)    { return 444; }
#   utility-block  -> if ($is_ai_utility) { return 444; }
# A site with no record keeps the global defaults.  No SSH/server-IP anti-lockout
# logic — that is an ip_access (IP allow/deny) concern, irrelevant to AI classes.

# Shared advisory lock so all BOA nginx-config writers (ip_access /
# cloudflare_realip / nginx_deny / ai_policy) never overlap their
# configtest+reload; wait up to 30s, then skip this run and retry next tick.
_lock_file="/run/boa_nginx_config.lock"
# Bump when the emitted directive shape changes, to force regeneration
# independent of the control-file mtime.
_emit_version="1"
_site_name_regex="^([a-zA-Z0-9_-]+\.)*[a-zA-Z0-9_-]+\.[a-zA-Z]{2,}$"

# Re-entrancy guard for the whole global run.
exec 9>"${_lock_file}" 2>/dev/null
if ! flock -w 30 9; then
  echo "Could not acquire the shared nginx-config lock; skipping this run."
  exit 0
fi

if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx not installed; nothing to do."
  exit 0
fi

_process_instance() {
  local _root="$1"
  local _input_file="${_root}/static/control/ai/policy.txt"
  local _ai_path="${_root}/config/includes/ai_policy"
  local _backup_dir="${_root}/undo"
  local _current_backup="${_backup_dir}/.nginx_ai_policy.current.bak.tar.gz"
  local _last_good_backup="${_backup_dir}/.nginx_ai_policy.last_good.bak.tar.gz"
  local _timestamp_file="${_ai_path}/.policy_last_mod_time"
  local _version_file="${_ai_path}/.emit_version"

  # Only instances with an activated control file and a real includes dir.
  [[ -f "${_input_file}" ]] || return 0
  [[ -d "${_root}/config/includes" ]] || return 0

  mkdir -p "${_ai_path}" "${_backup_dir}"

  # Change-gate: control-file mtime + emit version.
  local _current_mod_time _last_mod_time=0 _last_version=""
  _current_mod_time=$(stat -c %Y "${_input_file}" 2>/dev/null) || return 0
  [[ -f "${_timestamp_file}" ]] && _last_mod_time=$(cat "${_timestamp_file}" 2>/dev/null || echo 0)
  [[ -f "${_version_file}" ]] && _last_version=$(cat "${_version_file}" 2>/dev/null || echo "")
  if [[ "${_current_mod_time}" -le "${_last_mod_time}" && "${_last_version}" == "${_emit_version}" ]]; then
    return 0
  fi

  # Back up the instance's current fragments before regenerating.
  [[ -d "${_ai_path}" ]] && tar -czf "${_current_backup}" -C "${_ai_path}" . 2>/dev/null

  # Generate fragments; track configured sites for pruning.
  local -a _configured=()
  local _line _flag _site _body _frag _tmp
  while IFS= read -r _line; do
    _line="${_line%%#*}"
    [[ -z "${_line// /}" ]] && continue
    read -ra _fields <<< "${_line}"
    _site=$(echo "${_fields[0]}" | tr '[:upper:]' '[:lower:]')
    if [[ ! ${_site} =~ ${_site_name_regex} ]]; then
      echo "Invalid site name: ${_site} (${_root}). Skipping."
      continue
    fi
    _body=""
    for _flag in "${_fields[@]:1}"; do
      case "${_flag}" in
        train-allow)   _body+="set \$ai_train_allow 1;"$'\n' ;;
        search-block)  _body+="if (\$is_ai_search)  { return 444; }"$'\n' ;;
        user-block)    _body+="if (\$is_ai_user)    { return 444; }"$'\n' ;;
        utility-block) _body+="if (\$is_ai_utility) { return 444; }"$'\n' ;;
        *) echo "Unknown policy flag '${_flag}' for ${_site} (${_root}). Skipping flag." ;;
      esac
    done
    if [[ -z "${_body}" ]]; then
      echo "No valid policy flags for ${_site} (${_root}); no fragment written."
      continue
    fi
    _frag="${_ai_path}/${_site}.conf"
    _tmp="${_ai_path}/.${_site}.tmp.$$"
    {
      echo "# Generated by /var/xdrago/ai_policy.sh — DO NOT EDIT BY HAND."
      echo "# Per-site AI policy for ${_site}."
      printf '%s' "${_body}"
    } > "${_tmp}"
    mv -f "${_tmp}" "${_frag}"
    _configured+=("${_site}")
  done < "${_input_file}"

  # Prune fragments for sites no longer present in the control file.
  local _f _base _keep _s
  for _f in "${_ai_path}"/*.conf; do
    [[ -e "${_f}" ]] || continue
    _base=$(basename "${_f}" .conf)
    _keep=""
    for _s in "${_configured[@]}"; do
      [[ "${_s}" == "${_base}" ]] && _keep="yes" && break
    done
    if [[ -z "${_keep}" ]]; then
      rm -f "${_f}"
      echo "Pruned stale AI policy fragment: ${_base}.conf (${_root})"
    fi
  done

  # Validate the whole host nginx config; revert THIS instance on failure.
  local _ct
  _ct=$(service nginx configtest 2>&1)
  if [[ $? -ne 0 ]]; then
    echo "Nginx configtest failed after AI policy update (${_root}): ${_ct}"
    if [[ -f "${_last_good_backup}" ]]; then
      echo "Reverting ${_root} AI policy to last known good."
      rm -f "${_ai_path}"/*.conf
      tar -xzf "${_last_good_backup}" -C "${_ai_path}" 2>/dev/null
      service nginx reload
    fi
    return 1
  fi

  if ! service nginx reload; then
    echo "Nginx reload failed after AI policy update (${_root}); reverting."
    if [[ -f "${_last_good_backup}" ]]; then
      rm -f "${_ai_path}"/*.conf
      tar -xzf "${_last_good_backup}" -C "${_ai_path}" 2>/dev/null
      service nginx reload
    fi
    return 1
  fi

  # Success: refresh this instance's last-good backup + change-gate markers.
  tar -czf "${_last_good_backup}" -C "${_ai_path}" . 2>/dev/null
  echo "${_current_mod_time}" > "${_timestamp_file}"
  echo "${_emit_version}" > "${_version_file}"
  echo "AI policy updated (${_root}): ${_configured[*]:-none}; Nginx reloaded."
  return 0
}

# Loop over every Octopus instance (skip the 'arch' mounted-backup pseudo-user).
for _root in /data/disk/*; do
  [[ -d "${_root}" ]] || continue
  [[ "$(basename "${_root}")" == "arch" ]] && continue
  _process_instance "${_root}"
done

exit 0
