#!/bin/bash

# Generate the nginx realip trusted-source include from Cloudflare's published
# edge ranges, so `set_real_ip_from <range>` + `real_ip_header CF-Connecting-IP`
# resolve $remote_addr to the real client on CF-fronted vhosts (rate-limit keys,
# logs and deny then key on the visitor, not the CF edge).
#
# Idempotent: only rewrites the include and reloads nginx when the fetched
# ranges actually change.  Safe on non-CF boxes: declaring CF ranges as trusted
# is inert unless a request actually arrives from one of them, so realip never
# triggers for direct traffic.
#
# The realip directives and the wildcard `include .../nginx_cloudflare_real_ip.c*`
# live in the generated nginx server config (Provision server.tpl.php); this tool
# only maintains the ranges file that include consumes.

_out_dir="/data/conf"
_out_file="${_out_dir}/nginx_cloudflare_real_ip.conf"
# Leading-dot tmp/backup names so the `.c*` include glob never picks them up
# (nginx glob skips dotfiles); tmp stays in-dir so the install mv is atomic.
_tmp_file="${_out_dir}/.nginx_cloudflare_real_ip.tmp.$$"
_backup_file="${_out_dir}/.nginx_cloudflare_real_ip.last_good.conf"
_lock_file="/run/cloudflare_realip.lock"
_min_ranges=8

# Cloudflare publishes its ranges at these no-auth endpoints (same source the
# csf.allow whitelist in *-water.sh uses); the JSON API carries both families.
_cf_v4_url="https://www.cloudflare.com/ips-v4"
_cf_v6_url="https://www.cloudflare.com/ips-v6"
_cf_json_url="https://api.cloudflare.com/client/v4/ips"

# Validators (the safety net — only validated CIDRs are ever written).
_is_ipv4_cidr() { [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$ ]]; }
_is_ipv6_cidr() { [[ "$1" =~ ^[0-9a-fA-F:]*:[0-9a-fA-F:]*/[0-9]{1,3}$ ]]; }

# Global nginx config tool: only meaningful where nginx is installed.
if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx not installed; nothing to do."
  exit 0
fi

# Re-entrancy guard: skip this tick if a previous run is still active.
exec 9>"${_lock_file}" 2>/dev/null
if ! flock -n 9; then
  echo "Another cloudflare_realip run is active. Skipping."
  exit 0
fi

mkdir -p "${_out_dir}"

_fetch_cf_ranges() {
  local _v4 _v6 _json
  _v4=$(curl -k -sL --max-time 20 "${_cf_v4_url}" 2>/dev/null \
    | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | sort -u)
  _v6=$(curl -k -sL --max-time 20 "${_cf_v6_url}" 2>/dev/null \
    | grep -oiE '[0-9a-f:]*:[0-9a-f:]*/[0-9]{1,3}' | sort -u)
  if [[ -z "${_v4}" ]]; then
    echo "cloudflare ips-v4 endpoint failed; falling back to JSON API" >&2
    _json=$(curl -k -s --max-time 20 "${_cf_json_url}" 2>/dev/null)
    _v4=$(echo "${_json}" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | sort -u)
    [[ -z "${_v6}" ]] && _v6=$(echo "${_json}" \
      | grep -oiE '[0-9a-f:]*:[0-9a-f:]*/[0-9]{1,3}' | sort -u)
  fi
  printf '%s\n%s\n' "${_v4}" "${_v6}"
}

_raw_ranges=$(_fetch_cf_ranges | grep -v '^$' | sort -u)

# Never wipe a known-good include on a failed/empty fetch.
if [[ -z "${_raw_ranges}" ]]; then
  echo "No Cloudflare ranges fetched; leaving existing include untouched."
  exit 1
fi

{
  echo "# Cloudflare trusted edge ranges for nginx realip."
  echo "# Generated by /var/xdrago/cloudflare_realip.sh -- DO NOT EDIT BY HAND."
  echo "# Source: ${_cf_v4_url} , ${_cf_v6_url} (JSON fallback ${_cf_json_url})."
  while IFS= read -r _cidr; do
    [[ -z "${_cidr}" ]] && continue
    if _is_ipv4_cidr "${_cidr}" || _is_ipv6_cidr "${_cidr}"; then
      echo "set_real_ip_from ${_cidr};"
    else
      echo "cloudflare_realip: skipped invalid range: ${_cidr}" >&2
    fi
  done <<< "${_raw_ranges}"
} > "${_tmp_file}"

# Guard against a partial fetch silently shrinking the trust list.
_count=$(grep -c '^set_real_ip_from ' "${_tmp_file}" 2>/dev/null)
if [[ "${_count}" -lt "${_min_ranges}" ]]; then
  echo "Only ${_count} ranges parsed (< ${_min_ranges}); refusing to apply."
  rm -f "${_tmp_file}"
  exit 1
fi

# Change-gate: identical to the live include -> nothing to do (no reload).
if [[ -f "${_out_file}" ]] && cmp -s "${_tmp_file}" "${_out_file}"; then
  echo "Cloudflare ranges unchanged (${_count} entries). Nothing to do."
  rm -f "${_tmp_file}"
  exit 0
fi

# Back up the current good include, then atomically install the new one.
[[ -f "${_out_file}" ]] && cp -a "${_out_file}" "${_backup_file}"
mv -f "${_tmp_file}" "${_out_file}"

# Validate the whole nginx config; revert on failure.
_configtest=$(service nginx configtest 2>&1)
if [[ $? -ne 0 ]]; then
  echo "Nginx configtest failed after updating Cloudflare ranges: ${_configtest}"
  if [[ -f "${_backup_file}" ]]; then
    echo "Reverting to the last known good Cloudflare ranges include."
    cp -a "${_backup_file}" "${_out_file}"
  else
    echo "No backup to revert to; removing the new include."
    rm -f "${_out_file}"
  fi
  exit 1
fi

# Reload nginx; revert on failure.
if ! service nginx reload; then
  echo "Nginx reload failed; reverting Cloudflare ranges include."
  if [[ -f "${_backup_file}" ]]; then
    cp -a "${_backup_file}" "${_out_file}"
    service nginx reload
  fi
  exit 1
fi

echo "Cloudflare realip ranges updated (${_count} entries) and Nginx reloaded."
exit 0
