#!/bin/bash

# nginx_deny6.sh — the IPv6 counterpart of nginx_deny.sh.  csf is IPv4-only, so an
# IPv6 web offender detected by scan_nginx cannot be banned at the firewall;
# scan_nginx instead appends it (with an expiry) to an nginx-native store, and this
# tool prunes the expired entries and emits the still-active ones as `<ip6> 1;`
# into /data/conf/nginx_banned_ips.conf6 — picked up by the SAME
# `geo $remote_addr $is_banned` set (its wildcard `nginx_banned_ips.c*` include
# already covers this file) that nginx_deny.sh feeds for IPv4, and dropped with a
# 444 by the guard in the vhost template.  Idempotent: only rewrites + reloads
# when the set changes.
#
# IPv6 can only reach $remote_addr via the trusted realip proxy (BOA disables IPv6
# server-side and pins realip to the Cloudflare ranges), so a banned v6 is always
# the real client, never a spoofable direct peer.
#
# Store (written by scan_nginx.sh, pruned here): lines `<ip6>|<expiry-epoch>`.
# A re-offence appends a fresh expiry; the max per IP wins; expired IPs drop out
# on the next run (the self-expiry that csf provides for the IPv4 side).

_store="/var/xdrago/monitor/log/web6.tempban"
_out_dir="/data/conf"
_out_file="${_out_dir}/nginx_banned_ips.conf6"
# Leading-dot tmp/backup so the `nginx_banned_ips.c*` include glob never picks
# them up; in-dir so the install mv is atomic.
_tmp_file="${_out_dir}/.nginx_banned_ips6.tmp.$$"
_backup_file="${_out_dir}/.nginx_banned_ips6.last_good.conf"
_store_tmp="${_store}.tmp.$$"
# Shared advisory lock so all BOA nginx-config writers (ip_access /
# cloudflare_realip / nginx_deny / nginx_deny6 / ai_policy / user_admin_access)
# never overlap their configtest+reload; wait up to 30s, then skip and retry.
_lock_file="/run/boa_nginx_config.lock"

# Strict IPv6 (address-only) validator — a subset of what nginx accepts, so a
# malformed token in the store can never fail the box-wide configtest.
_hex="[0-9A-Fa-f]{1,4}"
_ipv4_octet="(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])"
_ipv4="(${_ipv4_octet}\.){3}${_ipv4_octet}"
_ipv6_regex="^((${_hex}:){7}${_hex}|(${_hex}:){1,7}:|(${_hex}:){1,6}:${_hex}|(${_hex}:){1,5}(:${_hex}){1,2}|(${_hex}:){1,4}(:${_hex}){1,3}|(${_hex}:){1,3}(:${_hex}){1,4}|(${_hex}:){1,2}(:${_hex}){1,5}|${_hex}:((:${_hex}){1,6})|:((:${_hex}){1,7}|:)|::(ffff(:0{1,4})?:)?(${_ipv4})|(${_hex}:){1,4}:(${_ipv4}))$"
_is_v6() { [[ "$1" == *:* && "$1" =~ ${_ipv6_regex} ]]; }

if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx not installed; nothing to do."
  exit 0
fi

exec 9>"${_lock_file}" 2>/dev/null
if ! flock -w 30 9; then
  echo "Could not acquire the shared nginx-config lock; skipping this run."
  exit 0
fi

mkdir -p "${_out_dir}"

_now=$(date +%s)

# Read the store into ip -> max future expiry (drops expired + collapses the
# duplicate/refreshed lines scan_nginx appends).
declare -A _EXP
if [[ -f "${_store}" ]]; then
  while IFS='|' read -r _ip _exp; do
    _is_v6 "${_ip}" || continue
    [[ "${_exp}" =~ ^[0-9]+$ ]] || continue
    (( _exp > _now )) || continue
    if [[ -z "${_EXP[${_ip}]:-}" ]] || (( _exp > _EXP[${_ip}] )); then
      _EXP[${_ip}]="${_exp}"
    fi
  done < "${_store}"

  # Rewrite the pruned store (surviving entries only) atomically. This is the
  # actual ban self-expiry. A concurrent scan_nginx append that lands between the
  # read above and this mv is lost, but the offender is re-detected on the next
  # ~5s scan, so it self-heals.
  {
    for _ip in "${!_EXP[@]}"; do echo "${_ip}|${_EXP[${_ip}]}"; done
  } > "${_store_tmp}"
  mv -f "${_store_tmp}" "${_store}"
fi

# Nothing banned and no stale output to clear -> done (leave the include glob to
# match zero files rather than write an empty one).
if (( ${#_EXP[@]} == 0 )) && [[ ! -f "${_out_file}" ]]; then
  exit 0
fi

# Build the geo fragment; entries sorted so an unchanged ban set yields a
# byte-identical file (stable change-gate, no needless reload).
{
  echo "# nginx realip-keyed IPv6 web deny set — generated by /var/xdrago/nginx_deny6.sh."
  echo "# DO NOT EDIT BY HAND.  Mirrors scan_nginx's nginx-native IPv6 ban store"
  echo "# (${_store}).  Consumed by the same geo \$is_banned map as the IPv4 set."
  for _ip in "${!_EXP[@]}"; do echo "${_ip} 1;"; done | sort
} > "${_tmp_file}"

# Change-gate: identical to the live file -> nothing to do (no reload).
if [[ -f "${_out_file}" ]] && cmp -s "${_tmp_file}" "${_out_file}"; then
  rm -f "${_tmp_file}"
  exit 0
fi

# Back up current, install new atomically, validate, reload, revert on failure.
[[ -f "${_out_file}" ]] && cp -a "${_out_file}" "${_backup_file}"
mv -f "${_tmp_file}" "${_out_file}"

_configtest=$(service nginx configtest 2>&1)
if [[ $? -ne 0 ]]; then
  echo "Nginx configtest failed after IPv6 deny-set update: ${_configtest}"
  if [[ -f "${_backup_file}" ]]; then
    echo "Reverting to the last known good IPv6 deny set."
    cp -a "${_backup_file}" "${_out_file}"
  else
    : > "${_out_file}"
  fi
  exit 1
fi

if ! service nginx reload; then
  echo "Nginx reload failed; reverting IPv6 deny set."
  if [[ -f "${_backup_file}" ]]; then
    cp -a "${_backup_file}" "${_out_file}"
    service nginx reload
  fi
  exit 1
fi

_count=$(grep -c ' 1;$' "${_out_file}" 2>/dev/null)
echo "nginx IPv6 web deny set updated (${_count} entr$([[ "${_count}" == "1" ]] && echo y || echo ies)); Nginx reloaded."
exit 0
