#!/bin/bash

# nginx_deny.sh — mirror BOA's WEB abuse bans into an nginx realip-keyed geo
# deny set, so a banned real-client IP is dropped at nginx (444) even when it
# arrives via Cloudflare — where an origin csf/iptables ban (which only sees the
# CF edge) does not bite.  Idempotent: only rewrites + reloads when the set
# changes.  The nginx side (the geo map + the `if ($is_banned) return 444;`
# guard + the wildcard include of the file written here) lives in the Provision
# templates; this tool only maintains /data/conf/nginx_banned_ips.conf.
#
# Sources (web bans only — ssh/ftp bans work at the csf network layer since they
# are not Cloudflare-proxied):
#   /var/lib/csf/csf.tempban  rows `epoch|ip|port|dir|ttl|comment` with port
#                             80 or 443  (the active 15-min web temp bans from
#                             guest-fire.sh)
#   /etc/csf/csf.deny         lines whose comment is "Brute force Web Server"
#                             (guest-water.sh's persistent web-offender
#                             escalations; this deliberately excludes the
#                             "SSH Server" / "FTP Server" entries and the broad
#                             "SSH/Web Server attacks" blocklist CIDRs)
# The set self-expires: csf drops expired tempban rows and the next run drops
# them from the geo file.

_tempban="/var/lib/csf/csf.tempban"
_csf_deny="/etc/csf/csf.deny"
_web_deny_match="Brute force Web Server"
_out_dir="/data/conf"
_out_file="${_out_dir}/nginx_banned_ips.conf"
# Leading-dot tmp/backup so the `.c*` include glob never picks them up; in-dir
# so the install mv is atomic.
_tmp_file="${_out_dir}/.nginx_banned_ips.tmp.$$"
_backup_file="${_out_dir}/.nginx_banned_ips.last_good.conf"
_lock_file="/run/nginx_deny.lock"

# Accept a bare IPv4 or an IPv4 CIDR (geo handles both); reject anything else
# (IPv6, hostnames, junk) — scan_nginx/csf web bans here are IPv4.
_is_ipv4_or_cidr() { [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]]; }

if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx not installed; nothing to do."
  exit 0
fi

exec 9>"${_lock_file}" 2>/dev/null
if ! flock -n 9; then
  echo "Another nginx_deny run is active. Skipping."
  exit 0
fi

mkdir -p "${_out_dir}"

_collect() {
  # Active WEB temp bans: csf.tempban rows whose port (field 3) is 80 or 443.
  if [[ -f "${_tempban}" ]]; then
    awk -F'|' '($3 == "80" || $3 == "443") { print $2 }' "${_tempban}" 2>/dev/null
  fi
  # Persistent WEB offenders: csf.deny lines tagged by water as Web Server.
  if [[ -f "${_csf_deny}" ]]; then
    grep -F "${_web_deny_match}" "${_csf_deny}" 2>/dev/null | awk '{ print $1 }'
  fi
}

_ips=$(_collect | sort -u)

{
  echo "# nginx realip-keyed web deny set — generated by /var/xdrago/nginx_deny.sh."
  echo "# DO NOT EDIT BY HAND.  Mirrors csf web temp bans (80/443) + csf.deny"
  echo "# 'Brute force Web Server' escalations.  Consumed by the geo \$is_banned map."
  while IFS= read -r _ip; do
    [[ -z "${_ip}" ]] && continue
    if _is_ipv4_or_cidr "${_ip}"; then
      echo "${_ip} 1;"
    fi
  done <<< "${_ips}"
} > "${_tmp_file}"

# Change-gate: identical to the live file -> nothing to do (no reload).
if [[ -f "${_out_file}" ]] && cmp -s "${_tmp_file}" "${_out_file}"; then
  rm -f "${_tmp_file}"
  exit 0
fi

# Back up current, install new atomically, validate, reload, revert on failure.
[[ -f "${_out_file}" ]] && cp -a "${_out_file}" "${_backup_file}"
mv -f "${_tmp_file}" "${_out_file}"

_configtest=$(service nginx configtest 2>&1)
if [[ $? -ne 0 ]]; then
  echo "Nginx configtest failed after deny-set update: ${_configtest}"
  if [[ -f "${_backup_file}" ]]; then
    echo "Reverting to the last known good deny set."
    cp -a "${_backup_file}" "${_out_file}"
  else
    : > "${_out_file}"
  fi
  exit 1
fi

if ! service nginx reload; then
  echo "Nginx reload failed; reverting deny set."
  if [[ -f "${_backup_file}" ]]; then
    cp -a "${_backup_file}" "${_out_file}"
    service nginx reload
  fi
  exit 1
fi

_count=$(grep -c ' 1;$' "${_out_file}" 2>/dev/null)
echo "nginx web deny set updated (${_count} entr$([[ "${_count}" == "1" ]] && echo y || echo ies)); Nginx reloaded."
exit 0
