###
### Secure HTTPS proxy (START) _oct_uid _oct_mail
###
server {
  listen                       _dedicated_ip:443 ssl;
  #listen                       _dedicated_ip:443 quic;
  http2                        on;
  #http3                        on;
  #http3_hq                     on;
  server_name                  _dedicated_sn;
  ssl_dhparam                  /etc/ssl/private/_domain_name.dhp;
  ssl_certificate              /etc/ssl/private/_domain_name.crt;
  ssl_certificate_key          /etc/ssl/private/_domain_name.key;
  ssl_session_timeout          5m;
  ssl_prefer_server_ciphers    on;
  ssl_conf_command Options     KTLS;
  keepalive_timeout            70;
  access_log                   off;
  log_not_found                off;


  ###
  ### Allow access to SQL Adminer css.
  ###
  location ^~ /sqladmin/adminer.css {
    alias /var/www/adminer/adminer.css;
    default_type text/css;
    try_files $uri =404;
  }

  ###
  ### Allow access to SQL Adminer.
  ###
  location ^~ /sqladmin {
    location ~* ^/sqladmin {
      alias /var/www/adminer;
      set_real_ip_from 127.0.0.1;
      set_real_ip_from _target_ip;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
      include /var/aegir/config/includes/ip_access/sqladmin*;
      index  index.php;
      try_files $uri /sqladmin/index.php?$query_string;
    }
  }

  ###
  ### Send all non-static requests to php-fpm.
  ###
  location = /sqladmin/index.php {
    set_real_ip_from 127.0.0.1;
    set_real_ip_from _target_ip;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
    include /var/aegir/config/includes/ip_access/sqladmin*;
    alias /var/www/adminer/index.php;
    include fastcgi_params;
    # Block https://httpoxy.org/ attacks.
    fastcgi_param  HTTP_PROXY "";
    fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param  SCRIPT_URL /sqladmin/;
    fastcgi_param  SCRIPT_URI $scheme://$host/sqladmin/;
    fastcgi_param  REDIRECT_STATUS 200;
    fastcgi_index  index.php;
    fastcgi_intercept_errors on;
    try_files $uri =404; ### check for existence of php file first
    fastcgi_pass 127.0.0.1:9000;
  }

  location / {
    proxy_pass                 http://_target_ip;
    proxy_redirect             off;
    gzip_vary                  off;
    proxy_buffering            off;
    proxy_set_header           Host              $host;
    proxy_set_header           X-Real-IP         $remote_addr;
    proxy_set_header           X-Forwarded-By    $server_addr:$server_port;
    proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header           X-Local-Proxy     $scheme;
    proxy_set_header           X-Forwarded-Proto $scheme;
    proxy_pass_header          Set-Cookie;
    proxy_pass_header          Cookie;
    proxy_pass_header          X-Accel-Expires;
    proxy_pass_header          X-Accel-Redirect;
    proxy_pass_header          X-This-Proto;
    proxy_connect_timeout      180;
    proxy_send_timeout         180;
    proxy_read_timeout         180;
  }
}
###
### Secure HTTPS proxy (END)
###
