#!/usr/bin/perl

###
### This is an auth abuse monitor for smtp.
###

$| = 1;
$this_filename = "hackmail";
$times = `date +%y%m%d-%H%M%S`;
chomp($times);
&makeactions;
print "CONTROL complete\n";
exit;

#############################################################################
sub makeactions
{
  if (-e "/var/xdrago/monitor/smtp.log") {
    $this_path = "/var/xdrago/monitor/smtp.log";
    open (NOT,"<$this_path");
    @banetable = <NOT>;
    close (NOT);
  }
  local(@MYARR) = `tail --lines=999 /var/log/mail.log 2>&1`;
  local($sumar,$maxnumber);
  foreach $line (@MYARR) {
    if ($line =~ /(Failed)|(identification)|(authentication)/i) {
      local($a, $b, $c, $d, $e, $f, $VISITORX, $rest) = split(/\s+/,$line) if ($line =~ /(failure)/i);
      chomp($VISITORX);
      local($a, $VISITOR) = split(/\[/,$VISITORX);
      $VISITOR =~ s/[^0-9\.]//g;
      if ($VISITOR =~ /^[0-9]/) {
        chomp($line);
        $li_cnt{$VISITOR}++;
      }
    }
  }
  foreach $VISITOR (sort keys %li_cnt) {
    $sumar = $sumar + $li_cnt{$VISITOR};
    local($thissumar) = $li_cnt{$VISITOR};
    $maxnumber = 10;
    local($blocked) = 0;
    &check_ip($VISITOR);
    if ($thissumar > $maxnumber) {
      if (!$blocked) {
        `echo "$VISITOR # [x$thissumar] $times" >> /var/xdrago/monitor/smtp.log`;
        `echo "$VISITOR # [x$thissumar] $times" >> /var/xdrago/monitor/$this_filename.archive.log`;
        if (-e "/etc/csf/csf.deny" && -e "/usr/sbin/csf" && !-e "/opt/fire.sh") {
          `/usr/sbin/csf -td $VISITOR 3600 -p 25`;
        }
      }
    }
  }
  print "\n===[$sumar]\tGLOBAL===\n\n";
  undef (%li_cnt);
}

#############################################################################
sub check_ip
{
  local($IP) = @_;
  if (-e "/var/xdrago/monitor/smtp.log") {
    foreach $banerecord (@banetable) {
      chomp ($banerecord);
      local($ifbanned, $rest) = split(/\s+/,$banerecord);
      $ifbanned =~ s/[^0-9\.]//g;
      if ($ifbanned eq $IP) {
        $blocked = 1;
        last;
      }
    }
  }
}
###EOF2013###
