#!/usr/bin/perl

###
### This is a httpd abuse monitor for nginx.
###

$| = 1;
$this_filename = "scan_nginx";
$times = `date +%y%m%d-%H%M%S`;
$myip = `hostname -i`;
chomp($times);
chomp($myip);
&makeactions;
print "CONTROL complete for $myip\n";
exit;

#############################################################################
sub makeactions
{
  if (-e "/var/xdrago/monitor/web.log") {
    $this_path = "/var/xdrago/monitor/web.log";
    open (NOT,"<$this_path");
    @banetable = <NOT>;
    close (NOT);
  }
  local(@MYARR) = `tail --lines=300 /var/log/nginx/access.log 2>&1`;
  local($mininumber,$critnumber,$alert);
  local($sumar,$li_cnt{$VISITOR},$sumarpx,$px_cnt{$PROXY});
  foreach $line (@MYARR) {
    local($VISITOR, $PROXY, $XREAL, $YREAL, $ZREAL, $RESTX) = split(/\s+/,$line);
    $VISITOR =~ s/[^0-9\.]//g;
    if ($VISITOR =~ /^((192.168.)|(172.16.)|(unknown)|(10.)|(127.0.))/)
    {
      $VISITOR = $PROXY;
      $PROXY = $XREAL;
      if ($VISITOR =~ /^((192.168.)|(172.16.)|(unknown)|(10.)|(127.0.))/)
      {
        $VISITOR = $XREAL;
        $PROXY = $YREAL;
        if ($VISITOR =~ /^((192.168.)|(172.16.)|(unknown)|(10.)|(127.0.))/)
        {
          $VISITOR = $YREAL;
          $PROXY = $ZREAL;
          if ($VISITOR =~ /^((192.168.)|(172.16.)|(unknown)|(10.)|(127.0.))/)
          {
            $VISITOR = $ZREAL;
          }
        }
      }
    }
    $VISITOR =~ s/[^0-9\.]//g;
    if ($VISITOR !~ /^((192.168.)|(172.16.)|(10.)|(127.0.))/ && $VISITOR =~ /^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/) {
      chomp($line);
      if ($line =~ /(GET|HEAD|POST)/) {
        if ($line =~ /POST \/([a-z]{2}\/)?(batch|advagg)|((GET|POST) \/([a-z]{2}\/)?(system|admin|app|ckeditor)\/|files\/(imagecache|styles|progress)|plupload|api\/rest|GET \/hosting|\/(ajax|autocomplete)\/)/) {
          print "Not Counted Request URI: $line\n";
        }
        else {
          $li_cnt{$VISITOR}++;
        }
        $li_cnt{$VISITOR} = $li_cnt{$VISITOR} + 1 if ($line =~ /(POST)/);
      }
      else {
        print "Not Supported Request Type: $line\n";
      }
    }
    $PROXY =~ s/[^0-9\.]//g;
    if ($PROXY ne $VISITOR && $PROXY !~ /^((192.168.)|(172.16.)|(10.)|(127.0.))/ && $PROXY =~ /^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/) {
      chomp($line);
      if ($line =~ /(GET|HEAD|POST)/) {
        if ($line =~ /POST \/([a-z]{2}\/)?(batch|advagg)|((GET|POST) \/([a-z]{2}\/)?(system|admin|app|ckeditor)\/|files\/(imagecache|styles|progress)|plupload|api\/rest|GET \/hosting|\/(ajax|autocomplete)\/)/) {
          print "Not Counted Request URI: $line\n";
        }
        else {
          $px_cnt{$PROXY}++;
        }
        $px_cnt{$PROXY} = $px_cnt{$PROXY} + 1 if ($line =~ /(POST)/);
      }
      else {
        print "Not Supported Request Type: $line\n";
      }
    }
  }
  foreach $VISITOR (sort keys %li_cnt) {
    $sumar = $sumar + $li_cnt{$VISITOR};
    local($thissumar) = $li_cnt{$VISITOR};
    $mininumber = 10;   ### default: 10
    $critnumber = 300;  ### default: 300
    $critnumber = 888 if ($VISITOR =~ /^($myip)$/); ### default for server IP
    local($blocked) = 0;
    &check_ip($VISITOR);
    if ($thissumar > $critnumber) {
      if (!$blocked) {
        `echo "$VISITOR # [x$thissumar] $times" >> /var/xdrago/monitor/web.log`;
        `echo "$VISITOR # [x$thissumar] $times" >> /var/xdrago/monitor/$this_filename.archive.log`;
        if (-e "/etc/csf/csf.deny" && -e "/usr/sbin/csf" && !-e "/opt/fire.sh") {
          `/usr/sbin/csf -td $VISITOR 3600 -p 80`;
        }
      }
    }
  }
  foreach $PROXY (sort keys %px_cnt) {
    $sumarpx = $sumarpx + $px_cnt{$PROXY};
    local($thissumarpx) = $px_cnt{$PROXY};
    $mininumber = 10;   ### default: 10
    $critnumber = 300;  ### default: 300
    $critnumber = 888 if ($PROXY =~ /^($myip)$/); ### default for server IP
    local($blocked) = 0;
    &check_ip($PROXY);
    if ($thissumarpx > $critnumber) {
      if (!$blocked) {
        `echo "$PROXY # [x$thissumarpx] $times" >> /var/xdrago/monitor/web.log`;
        `echo "$PROXY # [x$thissumarpx] $times" >> /var/xdrago/monitor/$this_filename.archive.log`;
        if (-e "/etc/csf/csf.deny" && -e "/usr/sbin/csf" && !-e "/opt/fire.sh") {
          `/usr/sbin/csf -td $PROXY 3600 -p 80`;
        }
      }
    }
  }
  print "\n===[$sumar]\tGLOBAL===";
  print "\n===[$sumarpx]\tGLOBAL===\n";
  undef (%li_cnt);
  undef (%px_cnt);
}

#############################################################################
sub check_ip
{
  local($IP) = @_;
  if (-e "/var/xdrago/monitor/web.log") {
    foreach $banerecord (@banetable) {
      chomp ($banerecord);
      local($ifbanned, $rest) = split(/\s+/,$banerecord);
      $ifbanned =~ s/[^0-9\.]//g;
      if ($ifbanned eq $IP) {
        $blocked = 1;
        last;
      }
    }
  }
}
###EOF2012###
