#!/usr/bin/perl

$| = 1;
if (-f "/var/run/boa_wait.pid") {exit;}
$status="CLEAN";
&makeactions;
if ($status ne "CLEAN") {
  `perl /var/xdrago/checksql.cgi`;
  `touch /var/xdrago/log/last-sqlcheck-found-problem`;
}
else {
  `touch /var/xdrago/log/last-sqlcheck-clean`;
}
exit;

#############################################################################
sub makeactions
{
local(@MYARR) = `tail --lines=200 /var/log/syslog 2>&1`;
  foreach $line (@MYARR) {
    if ($line =~ /(Checking table)/i || $line =~ /(is marked as crashed)/i) {
      $status="ERROR";
    }
  }
}
###EOF2012###
