###
### Adminer SQL Manager Redirect to HTTPS.
###
server {
  listen                       127.0.0.1:80;
  server_name                  adminer_name;
  # Disable access logs for this server block
  access_log off;
  log_not_found off;
  return 301 https://$host$request_uri;
}

###
### Adminer SQL Manager HTTPS Only.
###
server {
  include                      fastcgi_params;
  fastcgi_param                SCRIPT_FILENAME $document_root$fastcgi_script_name;
  fastcgi_param                HTTPS on;
  limit_conn                   limreq 555;
  listen                       127.0.0.1:443 ssl;
  http2                        on;
  server_name                  adminer_name;
  root                         /var/www/adminer;
  index                        index.php index.html;
  ssl_dhparam                  /etc/ssl/private/nginx-wild-ssl.dhp;
  ssl_certificate              /etc/ssl/private/nginx-wild-ssl.crt;
  ssl_certificate_key          /etc/ssl/private/nginx-wild-ssl.key;
  ssl_session_timeout          5m;
  if ($is_crawler) {
    return 444;
  }
  include                      /var/aegir/config/includes/ip_access/sqladmin*;
  include                      /var/aegir/config/includes/nginx_compact_include.conf;
}
