#!/bin/bash

### BEGIN INIT INFO
# Provides:          clean-boa-env
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: safeguard to remove auto-healing pid files after reboot etc.
# Description:       safeguard to remove auto-healing pid files after reboot etc.
### END INIT INFO

PATH=/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/libexec
NAME=clean-boa-env
DESC=clean-boa-env
PIDFILE=/run/clean-boa-env.pid

case "$1" in
  start)
    echo -n "Starting $DESC: "
    if [ -L "/bin/sh" ]; then
      _WEB_SH="$(readlink -n /bin/sh)"
      if [ -x "/bin/dash" ] || [ -x "/usr/bin/dash" ]; then
        if [ "${_WEB_SH}" != "/bin/dash" ]; then
          if [ -x "/usr/bin/dash" ] && [ ! -L "/usr/bin/dash" ]; then
            if [ -L "/usr/bin/sh" ]; then
              ln -sfn /usr/bin/dash /usr/bin/sh
            fi
            if [ -L "/bin/sh" ]; then
              ln -sfn /usr/bin/dash /bin/sh
            fi
          fi
          if [ -x "/bin/dash" ] && [ ! -L "/bin/dash" ]; then
            if [ -L "/usr/bin/sh" ]; then
              ln -sfn /bin/dash /usr/bin/sh
            fi
            if [ -L "/bin/sh" ]; then
              ln -sfn /bin/dash /bin/sh
            fi
          fi
        fi
      elif [ -x "/bin/bash" ] || [ -x "/usr/bin/bash" ]; then
        if [ "${_WEB_SH}" != "/bin/bash" ]; then
          if [ -x "/usr/bin/bash" ] && [ ! -L "/usr/bin/bash" ]; then
            if [ -L "/usr/bin/sh" ]; then
              ln -sfn /usr/bin/bash /usr/bin/sh
            fi
            if [ -L "/bin/sh" ]; then
              ln -sfn /usr/bin/bash /bin/sh
            fi
          fi
          if [ -x "/bin/bash" ] && [ ! -L "/bin/bash" ]; then
            if [ -L "/usr/bin/sh" ]; then
              ln -sfn /bin/bash /usr/bin/sh
            fi
            if [ -L "/bin/sh" ]; then
              ln -sfn /bin/bash /bin/sh
            fi
          fi
        fi
      fi
    fi
    _RAM_AUTO_FILE="/sys/devices/system/memory/auto_online_blocks"
    if [ -f "${_RAM_AUTO_FILE}" ]; then
      if grep -qx offline "${_RAM_AUTO_FILE}"; then
        echo online > "${_RAM_AUTO_FILE}"
      fi
    fi
    for _CPU_DIR in /sys/devices/system/cpu/cpu[0-9]*
    do
      _CPU=${_CPU_DIR##*/}
      _CPU_STATE_FILE="${_CPU_DIR}/online"
      if [ -f "${_CPU_STATE_FILE}" ]; then
        if grep -qx 0 "${_CPU_STATE_FILE}"; then
          echo 1 > "${_CPU_STATE_FILE}"
        fi
      fi
    done
    for _RAM_DIR in /sys/devices/system/memory/memory[0-9]*
    do
      _RAM=${_RAM_DIR##*/}
      _RAM_STATE_FILE="${_RAM_DIR}/state"
      if [ -f "${_RAM_STATE_FILE}" ]; then
        if grep -qx offline "${_RAM_STATE_FILE}"; then
          echo online > "${_RAM_STATE_FILE}"
        fi
      fi
    done
    if [ -e "/root/.run-to-excalibur.cnf" ]; then
      if [ -x "/opt/local/bin/autoexcalibur" ]; then
        nohup /opt/local/bin/autoexcalibur > /dev/null 2>&1 &
      fi
    elif [ -e "/root/.run-to-daedalus.cnf" ]; then
      if [ -x "/opt/local/bin/autodaedalus" ]; then
        nohup /opt/local/bin/autodaedalus > /dev/null 2>&1 &
      fi
    elif [ -e "/root/.run-to-chimaera.cnf" ]; then
      if [ -x "/opt/local/bin/autochimaera" ]; then
        nohup /opt/local/bin/autochimaera > /dev/null 2>&1 &
      fi
    elif [ -e "/root/.run-to-beowulf.cnf" ]; then
      if [ -x "/opt/local/bin/autobeowulf" ]; then
        nohup /opt/local/bin/autobeowulf > /dev/null 2>&1 &
      fi
    fi
    touch $PIDFILE
    [ -e "/run/boa_wait.pid" ] && rm -f /run/boa_wait.pid
    [ -e "/run/boa_run.pid" ] && rm -f /run/boa_run.pid
    [ -e "/run/manage_ltd_users.pid" ] && rm -f /run/manage_ltd_users.pid
    [ -e "/run/daily-fix.pid" ] && rm -f /run/daily-fix.pid
    [ -e "/run/boa_cron_wait.pid" ] && rm -f /run/boa_cron_wait.pid
  ;;
  stop)
    echo -n "Stopping $DESC: "
    if [ -L "/bin/sh" ]; then
      _WEB_SH="$(readlink -n /bin/sh)"
      if [ -x "/bin/dash" ]; then
        if [ "${_WEB_SH}" != "/bin/dash" ]; then
          ln -sfn /bin/dash /bin/sh
          if [ -e "/usr/bin/sh" ]; then
            ln -sfn /bin/dash /usr/bin/sh
          fi
        fi
      else
        if [ "${_WEB_SH}" != "/bin/bash" ]; then
          ln -sfn /bin/bash /bin/sh
          if [ -e "/usr/bin/sh" ]; then
            ln -sfn /bin/bash /usr/bin/sh
          fi
        fi
      fi
    fi
    _REBOOT_ONE_TEST=$(ls -la /root/.run-auto-major-os-reboot*-one.cnf 2>&1)
    _REBOOT_TWO_TEST=$(ls -la /root/.run-auto-major-os-reboot*-two.cnf 2>&1)
    if [[ "${_REBOOT_ONE_TEST}" =~ "No such file" ]] \
      && [[ "${_REBOOT_TWO_TEST}" =~ "No such file" ]]; then
      service cron stop &> /dev/null
      killall cron &> /dev/null
      pkill -9 -f second.sh
      pkill -9 -f runner.sh
      pkill -9 -f minute.sh
      echo "Cron has been stopped"
      if [ ! -e "/root/.allow.clamav.cnf" ] || [ -e "/root/.deny.clamav.cnf" ]; then
        if [ -e "/etc/init.d/clamav-daemon" ]; then
          update-rc.d -f clamav-daemon remove &> /dev/null
        fi
        if [ -e "/etc/init.d/clamav-freshclam" ]; then
          update-rc.d -f clamav-freshclam remove &> /dev/null
        fi
      fi
      pkill -9 -f avahi-daemon
      pkill -9 -f clamd
      pkill -9 -f freshclam
      pkill -9 -f java
      rm -f /run/clamav/*
      echo "Java/Solr/Clamav have been stopped"
      service nginx stop &> /dev/null
      killall nginx &> /dev/null
      killall php &> /dev/null
      pkill -9 -f php-fpm
      echo "Nginx, PHP-CLI and PHP-FPM have been stopped"
      csf -df &> /dev/null
      csf -tf &> /dev/null
      echo "Firewall has been purged"
      if [ -e "/root/.my.pass.txt" ]; then
        _SQL_PSWD=$(cat /root/.my.pass.txt 2>/dev/null | tr -d '\n')
        _IS_MYSQLD_RUNNING=$(pgrep -f /usr/sbin/mysqld)
        if [ ! -z "${_IS_MYSQLD_RUNNING}" ] && [ ! -z "${_SQL_PSWD}" ]; then
          echo "Preparing MySQLD for quick shutdown..."
          _DBS_TEST="$(which mysql)"
          if [ ! -z "${_DBS_TEST}" ]; then
            _DB_SERVER_TEST=$(mysql -V 2>&1)
          fi
          if [[ "${_DB_SERVER_TEST}" =~ "Ver 8.4." ]]; then
            _DB_V=8.4
          elif [[ "${_DB_SERVER_TEST}" =~ "Ver 8.0." ]]; then
            _DB_V=8.0
          elif [[ "${_DB_SERVER_TEST}" =~ "Distrib 5.7." ]]; then
            _DB_V=5.7
          fi
          mysql -u root -e "SET GLOBAL innodb_max_dirty_pages_pct = 0;" &> /dev/null
          mysql -u root -e "SET GLOBAL innodb_change_buffering = 'none';" &> /dev/null
          mysql -u root -e "SET GLOBAL innodb_buffer_pool_dump_at_shutdown = 1;" &> /dev/null
          mysql -u root -e "SET GLOBAL innodb_io_capacity = 2000;" &> /dev/null
          mysql -u root -e "SET GLOBAL innodb_io_capacity_max = 4000;" &> /dev/null
          if [ "${_DB_V}" = "5.7" ]; then
            mysql -u root -e "SET GLOBAL innodb_buffer_pool_dump_pct = 100;" &> /dev/null
            mysql -u root -e "SET GLOBAL innodb_buffer_pool_dump_now = ON;" &> /dev/null
          fi
          mysql -u root -e "SET GLOBAL innodb_fast_shutdown = 1;" &> /dev/null
          echo "Stopping MySQLD now..."
          service mysql stop &> /dev/null
          wait
          echo "MySQLD stopped"
        else
          echo "MySQLD already stopped"
        fi
      fi
    fi
    [ -e "/run/boa_wait.pid" ] && rm -f /run/boa_wait.pid
    [ -e "/run/boa_run.pid" ] && rm -f /run/boa_run.pid
    [ -e "/run/manage_ltd_users.pid" ] && rm -f /run/manage_ltd_users.pid
    [ -e "/run/daily-fix.pid" ] && rm -f /run/daily-fix.pid
    [ -e "/run/boa_cron_wait.pid" ] && rm -f /run/boa_cron_wait.pid
    rm -f $PIDFILE
  ;;

  restart|force-reload)
    ${0} stop
    ${0} start
  ;;

  *)
    echo "Usage: service $NAME {start|stop|restart|force-reload}" >&2
    exit 0
  ;;
esac

exit 0
