#!/bin/bash

action()
{
NOW_LOAD=`awk '{print $1*100}' /proc/loadavg`
CTL_LOAD=288
if [ $NOW_LOAD -lt $CTL_LOAD ] ; then
  echo load is $NOW_LOAD while maxload is $CTL_LOAD
  echo ... now doing CTL...
  su -s /bin/bash EDIT_USER -c "bash /data/disk/EDIT_USER/aegir.sh"
  touch /var/xdrago/log/last-run-EDIT_USER
  echo CTL done
else
  echo load is $NOW_LOAD while maxload is $CTL_LOAD
  echo ...we have to wait...
fi
}

if test -f /var/xdrago/log/optimize_mysql_ao.pid ; then
  touch /var/xdrago/log/wait-EDIT_USER
  exit
else
  action
fi
