#!/bin/bash

### BEGIN INIT INFO
# Provides:          clean-boa-env
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: safeguard to remove auto-healing pid files after reboot etc.
# Description:       safeguard to remove auto-healing pid files after reboot etc.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=clean-boa-env
DESC=clean-boa-env
PIDFILE=/var/run/clean-boa-env.pid

set -e

case "$1" in
  start)
    echo -n "Starting $DESC: "
    touch $PIDFILE
    if test -f /var/xdrago/log/optimize_mysql_ao.pid ; then
      rm -f /var/xdrago/log/optimize_mysql_ao.pid
      echo "$NAME done."
    else
      echo "$NAME nothing to do."
    fi
  ;;
  stop)
    echo -n "Stopping $DESC: "
    if test -f /var/xdrago/log/optimize_mysql_ao.pid ; then
      rm -f /var/xdrago/log/optimize_mysql_ao.pid
      echo "$NAME done."
    else
      echo "$NAME nothing to do."
    fi
    rm -f $PIDFILE
  ;;

  restart|force-reload)
    ${0} stop
    ${0} start
  ;;

  status)
    echo -n "$DESC status: "
    if test -f /var/xdrago/log/optimize_mysql_ao.pid ; then
      echo "fail"
    else
      echo "OK"
      exit 1
    fi
  ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
