#!/bin/sh

### BEGIN INIT INFO
# Provides:          php52-fpm
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php52-fpm
# Description:       starts the PHP FastCGI Process Manager daemon
### END INIT INFO
#
php_fpm_BIN=/opt/php52/bin/php-cgi
php_fpm_CONF=/opt/php52/etc/php52-fpm.conf
php_fpm_PID=/var/run/php52-fpm.pid
php_opts="--fpm-config $php_fpm_CONF -c /opt/php52/etc/php52.ini"

wait_for_pid () {
	try=0

	while test $try -lt 35 ; do

		case "$1" in
			'created')
			if [ -f "$2" ] ; then
				try=''
				break
			fi
			;;

			'removed')
			if [ ! -f "$2" ] ; then
				try=''
				break
			fi
			;;
		esac

		echo -n .
		try=`expr $try + 1`
		sleep 1

	done

}

case "$1" in
	start)
		echo -n "Starting php52-fpm "

		$php_fpm_BIN --fpm $php_opts

		if [ "$?" != 0 ] ; then
			echo " failed"
			exit 1
		fi

		wait_for_pid created $php_fpm_PID

		if [ -n "$try" ] ; then
			echo " failed"
			exit 1
		else
			echo " done"
		fi
	;;

	stop)
		echo -n "Shutting down php52-fpm "

		if [ ! -r $php_fpm_PID ] ; then
			echo "warning, no pid file found - php52-fpm is not running ?"
			exit 1
		fi

		kill -TERM `cat $php_fpm_PID`

		wait_for_pid removed $php_fpm_PID

		if [ -n "$try" ] ; then
			echo " failed"
			exit 1
		else
			echo " done"
		fi
	;;

	quit)
		echo -n "Gracefully shutting down php52-fpm "

		if [ ! -r $php_fpm_PID ] ; then
			echo "warning, no pid file found - php52-fpm is not running ?"
			exit 1
		fi

		kill -QUIT `cat $php_fpm_PID`

		wait_for_pid removed $php_fpm_PID

		if [ -n "$try" ] ; then
			echo " failed"
			exit 1
		else
			echo " done"
		fi
	;;

	restart)
		$0 stop
		$0 start
	;;

	reload)

		echo -n "Reload service php52-fpm "

		if [ ! -r $php_fpm_PID ] ; then
			echo "warning, no pid file found - php52-fpm is not running ?"
			exit 1
		fi

		kill -USR2 `cat $php_fpm_PID`

		echo " done"
	;;

	logrotate)

		echo -n "Re-opening php52-fpm log file "

		if [ ! -r $php_fpm_PID ] ; then
			echo "warning, no pid file found - php52-fpm is not running ?"
			exit 1
		fi

		kill -USR1 `cat $php_fpm_PID`

		echo " done"
	;;

	*)
		echo "Usage: $0 {start|stop|quit|restart|reload|logrotate}"
		exit 1
	;;

esac
