#!/bin/sh

### BEGIN INIT INFO
# Provides:          php53-fpm
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php53-fpm
# Description:       starts the PHP FastCGI Process Manager daemon
### END INIT INFO

export ZEND_DONT_UNLOAD_MODULES=1
prefix=/opt/local
exec_prefix=${prefix}
php_fpm_BIN=/opt/php53/sbin/php-fpm
php_fpm_CONF=/opt/php53/etc/php53-fpm.conf
php_fpm_PID=/var/run/php53-fpm.pid
php_opts="--fpm-config $php_fpm_CONF -c /opt/php53/etc/php53.ini"

case "$1" in

  start)
    echo -n "Starting php53-fpm..."
    rm -f $php_fpm_PID
    $php_fpm_BIN $php_opts
    if [ "$?" != 0 ] ; then
      echo " failed"
      exit 1
    fi
    echo " done"
  ;;

  stop)
    echo -n "Gracefully shutting down php53-fpm..."
    if [ ! -r $php_fpm_PID ] ; then
      echo "warning, no pid file found - php53-fpm not running ?"
      exit 1
    fi
    kill -QUIT `cat $php_fpm_PID`
    echo " done"
  ;;

  force-quit)
    echo -n "Terminating php53-fpm..."
    if [ ! -r $php_fpm_PID ] ; then
      echo "no pid file found - running killall -9 php-fpm"
      killall -9 php-fpm
    fi
    #kill -TERM `cat $php_fpm_PID`
    killall -9 php-fpm
    echo " done"
  ;;

  restart)
    $0 stop
    sleep 2
    $0 start
  ;;

  force-restart)
    $0 force-quit
    sleep 2
    $0 start
  ;;

  reload)
    echo -n "Reload service php53-fpm..."
    if [ ! -r $php_fpm_PID ] ; then
      echo "warning, no pid file found - php53-fpm not running ?"
      exit 1
    fi
    kill -USR2 `cat $php_fpm_PID`
    echo " done"
  ;;

  *)
    echo "Usage: $0 {start|stop|force-quit|restart|force-restart|reload}"
    exit 1
  ;;

esac
