#!/bin/bash

### BEGIN INIT INFO
#
# Provides:          Tomcat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network $named $time
# Should-Stop:       $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the Tomcat server daemon
# Description:       Controls the Tomcat server daemon "tomcat"
# processname:       tomcat
# pidfile:           /var/run/tomcat.pid
#
### END INIT INFO
#
ENABLED=0

if [ -f /etc/default/tomcat ]; then
  . /etc/default/tomcat
fi

if [ "$ENABLED" = "0" ]; then
  exit 0
fi

export JAVA_HOME=/usr/lib/jvm/java-6-openjdk/jre
export JAVA_OPTS="$JAVA_OPTS -Dsolr.solr.home=/opt/solr"
export CATALINA_OPTS="-Xms64m -Xmx256m"

case $1 in
start)
  su -s /bin/bash tomcat -c "sh /opt/tomcat6/bin/startup.sh"
  ;;
stop)
  su -s /bin/bash tomcat -c "sh /opt/tomcat6/bin/shutdown.sh"
  ;;
restart)
  su -s /bin/bash tomcat -c "sh /opt/tomcat6/bin/shutdown.sh"
  su -s /bin/bash tomcat -c "sh /opt/tomcat6/bin/startup.sh"
  ;;
esac
exit 0
