#!/usr/bin/perl

$| = 1;
$this_filename = "hackmail";
&makeactions;
print " CONTROL hack1 done_______________________\n ...\n";
exit;

#############################################################################
sub makeactions
{
  $this_path = "/var/xdrago/firewall/$this_filename";
  if (!-e "$this_path") {
    `echo "#!/bin/bash" >> /var/xdrago/firewall/$this_filename`;
    `echo " " >> /var/xdrago/firewall/$this_filename`;
  }
  open (NOT,"<$this_path");
  @banetable = <NOT>;
  close (NOT);
  local(@MYARR) = `tail --lines=999 /var/log/mail.log 2>&1`;
  local($maxnumber,$critnumber,$alert);
  local($sumar,$li_cnt{$DOMAIN},$li_cndx{$DOMAIN});
  foreach $line (@MYARR) {
    if ($line =~ /(Failed)|(identification)|(authentication)/i) {
      local($a, $b, $c, $d, $e, $f, $VISITORX, $rest) = split(/\s+/,$line) if ($line =~ /(failure)/i);
      chomp($VISITORX);
      local($a, $VISITOR) = split(/\[/,$VISITORX);
      $VISITOR =~ s/[^0-9\.]//g;
      if ($VISITOR =~ /^[0-9]/) {
        chomp($line);
        $li_cnt{$VISITOR}++;
      }
    }
  }
  foreach $VISITOR (sort keys %li_cnt) {
    $sumar = $sumar + $li_cnt{$VISITOR};
    local($thissumar) = $li_cnt{$VISITOR};
    $maxnumber = 10;
    local($blocked) = 0;
    &check_ip($VISITOR);
    if ($thissumar > $maxnumber && !$blocked) {
      &trash_it_action($VISITOR,$thissumar);
    }
  }
  print "\n===[$sumar]\tGLOBAL===\n\n";
  undef (%li_cnt);
}

#############################################################################
sub trash_it_action
{
  local($ABUSER,$COUNTER) = @_;
  local($proxy_host) = 0;
  local($REMOTE_HOST) = $ABUSER;
  local($machine) = $ABUSER;
  $machine =~ s/^\s+|\s+$//g;
  @bytes = split (/\./, $machine);
  $packaddr = pack ("C4", @bytes);
  if (!(($name, $altnames, $addrtype, $len, @addrlist) =
    gethostbyaddr ($packaddr, 2))) {
    $REMOTE_HOST = "";
  }
  else {
    $REMOTE_HOST = "$name";
  }
  if ($REMOTE_HOST !~ /(my-white-listed-host)/)
  {
    $now_is = `date +%y%m%d-%H%M%S`;
    chomp($now_is);
    print "$ABUSER [$COUNTER] recorded... $REMOTE_HOST\n";
    `/sbin/iptables -A INPUT -p tcp -s $ABUSER --dport 25 -j DROP` if (!$blocked);
    `echo "#-- BELOW --# $ABUSER [$COUNTER] recorded... [$now_is] $REMOTE_HOST" >> /var/xdrago/firewall/$this_filename`;
    `echo "/sbin/iptables -A INPUT -s $ABUSER -j DROP" >> /var/xdrago/firewall/$this_filename`;
    `echo " " >> /var/xdrago/firewall/$this_filename`;
  }
}

#############################################################################
sub check_ip
{
  local($IP) = @_;
  foreach $line (@banetable) {
    chomp ($line);
    if ($line =~ /(iptables)/) {
      local($a, $b, $c, $d, $EXISTS, $g, $h) = split(/\s+/,$line);
      if ($EXISTS eq $IP) {
        $blocked = 1;
        last;
      }
    }
  }
}
###EOF###
